/**
 *          FILENAME: about.routing.ts
 *             ROUTE: totalscope_webclient/src/app/modules/about/
 *            AUTHOR: ICI/MS
 *              WHAT: HANDLES THE ROUTING FOR THE ABOUT PAGE IN TOTALSCOPE.
 *               HOW: DEFINES THE ROUTE, CONFIGURES THE ANGULAR ROUTERMODULE TO USE THIS ROUTE, 
 *                    AND EXPORTS IT FOR USE IN OTHER PARTS OF THE APPLICATION, ENABLING THE DISPLAY OF THE "ABOUT" CONTENT 
 *                    WHEN THE ROOT URL IS ACCESSED.
 *   IMPORTING FILES: about.component.ts
 * SUBSCRIBING FILES: about.module.ts
 *  LAST COMMIT DATE: JUNE 15, 2023
 */

/**
 * NGMODULE | HELPS TO CONFIGURE THE INJECTOR AND THE COMPILER AND HELPS TO DEFINE OTHER MODULES THAT THE CURRENT MODULE DEPENDS ON.
 * ROUTERMODULE | HELPS TO DEFINE THE ROUTES FOR THE APPLICATION AND HELPS TO LINK THEM WITH THE CORRESPONDING COMPONENTS.
 * ROUTES | HELPS TO DEFINE THE PATH, THE COMPONENT THAT SHOULD BE LOADED WHEN THE PATH IS MATCHED.
 * AND ANY ADDITIONAL DATA THAT SHOULD BE PROVIDED TO THE COMPONENT.
 */
import {NgModule} from '@angular/core'
import {RouterModule, Routes} from '@angular/router'

/**
 * IMPORTS THE ABOUTCOMPONENT FROM THE ABOUT.COMPONENT FILE. 
 * ALLOWS THE ABOUTCOMPONENT TO BE USED IN THE CURRENT FILE.
 */
import {AboutComponent} from './about.component'

/**
 * CONFIGURES A SINGLE ROUTE TO RENDER THE ABOUTCOMPONENT WHEN THE ROOT URL IS ACCESSED.
 */
const routes: Routes = 
[
  {
    path: '', // MAIN PAGE
    component: AboutComponent, // SHOW ABOUT CONTENT HERE.
  },
]

/**
 * SETS UP APPLICATION ROUTING BY DEFINING AVAILABLE ROUTES, CONFIGURING THE ROUTERMODULE FOR ROUTING FUNCTIONALITY, 
 * AND EXPORTING IT FOR USE IN OTHER MODULES.
 */
@NgModule
({
  imports: [RouterModule.forChild (routes)], // LOADS SPECIFIC ROUTES FOR THIS MODULE.
  exports: [RouterModule], // MAKES ROUTING AVAILABLE TO OTHER PARTS OF THE APP.
})

/**
 * HANDLES ROUTING FOR THE ABOUT PAGE.
 */
export class AboutRoutingModule{}
