/**
 *          FILENAME: about.module.ts
 *             ROUTE: totalscope_webclient/src/app/modules/about/
 *            AUTHOR: ICI/SK
 *              WHAT: MANAGES THE FUNCTIONALITY AND DATA ASSOCIATED WITH THE ABOUT SECTION IN TOTALSCOPE.
 *               HOW: CONFIGURES ROUTING FOR THE ABOUTCOMPONENT, AND PROVIDES A STRUCTURE FOR ORGANIZING 
 *                    AND REUSING CODE RELATED TO THE ABOUT SECTION.
 *   IMPORTING FILES: about.component.ts | about.routing.ts
 * SUBSCRIBING FILES: app-routing.module.ts
 *  LAST COMMIT DATE: JUNE 15, 2023
 */

/**
 * IMPORTS THE COMMON AND CORE MODULES.
 * COMMONMODULE | PROVIDES A SET OF COMMON DIRECTIVES SUCH AS NGIF, AND NGFOR AND PIPES SUCH AS DATEPIP AND CURRENCYPIPE.
 * NGMODULE | SPECIFIES WHICH COMPONENTS, DIRECTIVES, AND PIPES ARE AVAILABLE TO OTHER MODULES.
 */ 
import {CommonModule} from '@angular/common'
import {NgModule} from '@angular/core'

/**
 * ABOUTCOMPONENT | DISPLAYS INFORMATION REGARDING TOTALSCOPE.
 * ABOUTROUTINGMODULE | PROVIDES ROUTING CONFIGURATION FOR THE ABOUTCOMPONENT.
 */
import {AboutComponent} from './about.component'
import {AboutRoutingModule} from './about.routing'

/**
 * @NGMODULE | DEFINES THE MODULE AND THE PROPERTIES OF THE MODULE.
 * DECLARATIONS | DECLARES THE COMPONENTS USED IN THE MODULE.
 * IMPORTS | IMPORTS OTHER MODULES USED IN THE APPLICATION
 */
@NgModule
({
  declarations: [AboutComponent],
  imports: [CommonModule, AboutRoutingModule],
})

/**
 * EXPORTS AN ABOUTMODULE CLASS FOR STORING "ABOUT" SECTION DATA AND METHODS FOR REUSE IN OTHER PARTS OF YOUR CODE.
 */
export class AboutModule{}
