/**
 *          FILENAME: register-routing.module.ts
 *             ROUTE: totalscope_webclient/src/app/modules/auth/register/
 *            AUTHOR: ICI/SZ
 *              WHAT: SETS UP AND CONFIGURES THE ROUTING SYSTEM FOR TOTALSCOPE.
 *               HOW: DEFINES THE ROUTES AND ASSOCIATES THEM WITH SPECIFIC COMPONENTS, 
 *                    AND THEN EXPORTS A MODULE THAT OTHER PARTS OF THE APPLICATION CAN USE TO ENABLE NAVIGATION 
 *                    AND DISPLAY THE APPROPRIATE COMPONENTS WHEN USERS NAVIGATE TO DIFFERENT PATHS WITHIN THE APPLICATION.
 *   IMPORTING FILES: company-type.component.ts | registration.component.ts
 * SUBSCRIBING FILES: register.module.ts | registration.component.ts 
 *  LAST COMMIT DATE: SEPTEMBER 12, 2023
 */

/**
 * NGMODULE | HELPS TO CONFIGURE THE INJECTOR AND THE COMPILER AND HELPS TO DEFINE OTHER MODULES THAT THE CURRENT MODULE DEPENDS ON.
 * ROUTERMODULE | HELPS TO DEFINE THE ROUTES FOR THE APPLICATION AND HELPS TO LINK THEM WITH THE CORRESPONDING COMPONENTS.
 * ROUTES | HELPS TO DEFINE THE PATH, THE COMPONENT THAT SHOULD BE LOADED WHEN THE PATH IS MATCHED.
 * AND ANY ADDITIONAL DATA THAT SHOULD BE PROVIDED TO THE COMPONENT.
 */
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';

/**
 * IMPORTS TWO COMPONENTS FROM DIFFERENT MODULES: 
 * CONTRACTORTYPECOMPONENT FROM THE CONTRACTOR-TYPE MODULE AND RegistrationComponent FROM THE CONTRACTOR MODULE.
 */
import {CompanyTypeComponent} from './company-type/company-type.component';
import {RegistrationComponent} from './contractor/registration.component';

/**
 * DEFINES THE WEB APPLICATION ROUTES USING AN ARRAY OF OBJECTS NAMED ROUTES, WHICH INCLUDES PATH AND COMPONENT FIELDS. 
 * THE FIRST ROUTE REDIRECTS USERS TO THE CONTRACTOR-TYPE PAGE WHEN THEY VISIT THE HOME PAGE (EMPTY PATH). 
 * THE SECOND ROUTE MAPS THE CONTRACTOR-TYPE PATH TO THE CONTRACTORTYPECOMPONENT, DISPLAYING IT WHEN USERS VISIT THAT PAGE. 
 * SIMILARLY, THE THIRD, FOURTH AND FIFTH ROUTE ASSOCIATES THE CONTRACTOR, CLAIMHANDLER AND PUBLICADJUSTER PATH WITH THE REGISTRATIONCOMPONENT, 
 * ENSURING IT'S SHOWN WHEN USERS SELECT THE COMPANY TYPE.
 */
const routes: Routes =
[
  {
  	/**
     * SETS UP AN ANGULAR ROUTE THAT REDIRECTS TO CONTRACTOR-TYPE FOR A FULL PATH MATCH WHEN THE PATH IS EMPTY.
     */
    path: '',
    redirectTo: 'company-type',
    pathMatch: 'full'
  },
  {
  	/**
     * SETS UP A ROUTE NAMED CONTRACTOR-TYPE LINKED TO THE CONTRACTORTYPECOMPONENT, MAKING IT THE COMPONENT TO DISPLAY
     * WHEN USERS VISIT THE CONTRACTOR-TYPE PATH.
     */
    path: 'company-type',
    component: CompanyTypeComponent
  },
  {
  	/**
     * ESTABLISHES A ROUTE NAMED "CONTRACTOR" FOR RENDERING THE "REGISTRATIONCOMPONENT" WHEN THE USER NAVIGATES TO "/CONTRACTOR" IN THE APP.
     */
    path: 'contractor/:step',
    component: RegistrationComponent
  },
  {
  	/**
     * ESTABLISHES A ROUTE NAMED "CONTRACTOR" FOR RENDERING THE "REGISTRATIONCOMPONENT" WHEN THE USER NAVIGATES TO "/CONTRACTOR" IN THE APP.
     */
    path: 'contractor',
    component: RegistrationComponent
  },
  {
  	/**
     * ESTABLISHES A ROUTE NAMED "CLAIMHANDLER" FOR RENDERING THE "REGISTRATIONCOMPONENT" WHEN THE USER NAVIGATES TO "/CLAIMHANDLER" IN THE APP.
     */
    path: 'claimhandler',
    component: RegistrationComponent
  },
  {
  	/**
     * ESTABLISHES A ROUTE NAMED "PUBLICADJUSTER" FOR RENDERING THE "REGISTRATIONCOMPONENT" WHEN THE USER NAVIGATES TO "/PUBLICADJUSTER" IN THE APP.
     */
    path: 'publicadjuster',
    component: RegistrationComponent
  }
];

/**
 * CONFIGURES ROUTES IN AN ANGULAR APPLICATION BY DEFINING AN ANGULAR MODULE. 
 * IT IMPORTS THE ROUTERMODULE TO SET UP ROUTES USING ROUTERMODULE.FORCHILD AND EXPORTS ROUTERMODULE FOR USE IN OTHER MODULES.
 */
@NgModule
({
  imports: [RouterModule.forChild (routes)],
  exports: [RouterModule]
})

/**
 * DEFINES THE REGISTERROUTINGMODULE CLASS FOR CREATING ROUTES FOR WEB APPLICATION NAVIGATION.
 */
export class RegisterRoutingModule{}
